selection_strategy: [random]
model_name: [DNN_MNIST]
dataset_name: [MNIST]
rounds: [50]
num_clients: [100]
local_epochs: [2]
batch_size: [128]
learning_rate: [1.0e-2]
seed: [42, 19, 27]
save_client_models: false
save_server_intermediate_models: false
reuse_client_model: true
keras_verbose: 0
max_concurrent_clients: 32

# --- Parâmetros da Simulação ---
attack_rates: [0.0, 0.2, 0.4, 0.6]
selection_fractions: [1.0]
non_iid: [false, true]
dirichlet_alpha: [0.1, 0.5]

# Pipelines de defesa mapeados do código
defense_pipelines:

  # --- Baselines Padrão ---
  Média Ponderada (Baseline):
    client_filters: []
    aggregation_strategy:
      name: FED_AVG
      params: {}
    global_model_filter: null

  Média Aparada:
    client_filters: []
    aggregation_strategy:
      name: TRIMMED_MEAN
      params:
        trim_ratio: 0.4
    global_model_filter: null

  Krum:
    client_filters:
      - name: KRUM
        params: {}
    aggregation_strategy:
      name: FED_AVG
    global_model_filter: null

  Multi-Krum:
    client_filters:
      - name: MULTI_KRUM
        params: {}
    aggregation_strategy:
      name: FED_AVG
    global_model_filter: null

  Clustering:
    client_filters:
      - name: CLUSTERING
        params: {}
    aggregation_strategy:
      name: FED_AVG
    global_model_filter: null

  # --- Distância (df) ---

  PCA Geometric Median Distance (nc=5, df=0.2):
    client_filters:
      - name: PCA_GEOMETRIC_MEDIAN_DISTANCE
        params:
          pca_layers: [0, 2, 4]
          n_components: 5
          warmup_rounds: 0
          discard_fraction: 0.2
    aggregation_strategy:
      name: FED_AVG
    global_model_filter: null
  
  PCA Geometric Median Distance (nc=5, df=0.4):
    client_filters:
      - name: PCA_GEOMETRIC_MEDIAN_DISTANCE
        params:
          pca_layers: [0, 2, 4]
          n_components: 5
          warmup_rounds: 0
          discard_fraction: 0.4
    aggregation_strategy:
      name: FED_AVG
    global_model_filter: null
  
  PCA Geometric Median Distance (nc=5, df=0.6):
    client_filters:
      - name: PCA_GEOMETRIC_MEDIAN_DISTANCE
        params:
          pca_layers: [0, 2, 4]
          n_components: 5
          warmup_rounds: 0
          discard_fraction: 0.6
    aggregation_strategy:
      name: FED_AVG
    global_model_filter: null
  
  # --- Distância (nc) ---

  PCA Geometric Median Distance (nc=2, df=0.4):
    client_filters:
      - name: PCA_GEOMETRIC_MEDIAN_DISTANCE
        params:
          pca_layers: [0, 2, 4]
          n_components: 2
          warmup_rounds: 0
          discard_fraction: 0.4
    aggregation_strategy:
      name: FED_AVG
    global_model_filter: null
  
  # PCA Geometric Median Distance (nc=5):
  #   client_filters:
  #     - name: PCA_GEOMETRIC_MEDIAN_DISTANCE
  #       params:
  #         pca_layers: [0, 2, 4]
  #         n_components: 5
  #         warmup_rounds: 0
  #         discard_fraction: 0.4
  #   aggregation_strategy:
  #     name: FED_AVG
  #   global_model_filter: null
  
  PCA Geometric Median Distance (nc=10, df=0.4):
    client_filters:
      - name: PCA_GEOMETRIC_MEDIAN_DISTANCE
        params:
          pca_layers: [0, 2, 4]
          n_components: 10
          warmup_rounds: 0
          discard_fraction: 0.4
    aggregation_strategy:
      name: FED_AVG
    global_model_filter: null

  # --- Direction (mc) ---
  
  PCA Geometric Median Direction (nc=5, mc=0):
    client_filters:
      - name: PCA_GEOMETRIC_MEDIAN_DIRECTION
        params:
          pca_layers: [0, 2, 4]
          n_components: 5
          warmup_rounds: 0
          selection_strategy: "min_cosine"
          min_cosine: 0.0
    aggregation_strategy:
      name: FED_AVG
    global_model_filter: null
  
  PCA Geometric Median Direction (nc=5, mc=-0.4):
    client_filters:
      - name: PCA_GEOMETRIC_MEDIAN_DIRECTION
        params:
          pca_layers: [0, 2, 4]
          n_components: 5
          warmup_rounds: 0
          selection_strategy: "min_cosine"
          min_cosine: -0.4
    aggregation_strategy:
      name: FED_AVG
    global_model_filter: null

  PCA Geometric Median Direction (nc=5, mc=-0.6):
    client_filters:
      - name: PCA_GEOMETRIC_MEDIAN_DIRECTION
        params:
          pca_layers: [0, 2, 4]
          n_components: 5
          warmup_rounds: 0
          selection_strategy: "min_cosine"
          min_cosine: -0.6
    aggregation_strategy:
      name: FED_AVG
    global_model_filter: null
  
  # --- Direction (df) ---
  
  PCA Geometric Median Direction (nc=5, df=0.2):
    client_filters:
      - name: PCA_GEOMETRIC_MEDIAN_DIRECTION
        params:
          pca_layers: [0, 2, 4]
          n_components: 5
          warmup_rounds: 0
          selection_strategy: "discard_fraction"
          discard_fraction: 0.2
    aggregation_strategy:
      name: FED_AVG
    global_model_filter: null
  
  PCA Geometric Median Direction (nc=5, df=0.4):
    client_filters:
      - name: PCA_GEOMETRIC_MEDIAN_DIRECTION
        params:
          pca_layers: [0, 2, 4]
          n_components: 5
          warmup_rounds: 0
          selection_strategy: "discard_fraction"
          discard_fraction: 0.4
    aggregation_strategy:
      name: FED_AVG
    global_model_filter: null

  PCA Geometric Median Direction (nc=5, df=0.6):
    client_filters:
      - name: PCA_GEOMETRIC_MEDIAN_DIRECTION
        params:
          pca_layers: [0, 2, 4]
          n_components: 5
          warmup_rounds: 0
          selection_strategy: "discard_fraction"
          discard_fraction: 0.6
    aggregation_strategy:
      name: FED_AVG
    global_model_filter: null
  
  # --- Direction (nc) ---

  PCA Geometric Median Direction (nc=2, mc=-0.4):
    client_filters:
      - name: PCA_GEOMETRIC_MEDIAN_DIRECTION
        params:
          pca_layers: [0, 2, 4]
          n_components: 2
          warmup_rounds: 0
          selection_strategy: "min_cosine"
          min_cosine: -0.4
    aggregation_strategy:
      name: FED_AVG
    global_model_filter: null
  
  # PCA Geometric Median Direction (nc=5):
  #   client_filters:
  #     - name: PCA_GEOMETRIC_MEDIAN_DIRECTION
  #       params:
  #         pca_layers: [0, 2, 4]
  #         n_components: 5
  #         warmup_rounds: 0
  #         selection_strategy: "min_cosine"
  #         min_cosine: -0.4
  #   aggregation_strategy:
  #     name: FED_AVG
  #   global_model_filter: null
  
  PCA Geometric Median Direction (nc=10, mc=-0.4):
    client_filters:
      - name: PCA_GEOMETRIC_MEDIAN_DIRECTION
        params:
          pca_layers: [0, 2, 4]
          n_components: 10
          warmup_rounds: 0
          selection_strategy: "min_cosine"
          min_cosine: -0.4
    aggregation_strategy:
      name: FED_AVG
    global_model_filter: null