services:
  server:
    build:
      dockerfile: dockerfiles/server.Dockerfile
    environment:
      - CUDA_VISIBLE_DEVICES=-1
    ports:
      - "8000:8000"
    volumes:
      - ./results:/app/results
    networks:
      - fl_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 4g

  # Clientes serão gerados dinamicamente pelo script run_experiment.sh
  # Exemplo de cliente
  client1:
    build:
      dockerfile: dockerfiles/client.Dockerfile
    depends_on:
      server:
        condition: service_healthy
    environment:
      - CLIENT_ID=1
      - SERVER_URL=http://server:8000
      - CUDA_VISIBLE_DEVICES=-1
    networks:
      - fl_network
    deploy:
      resources:
        limits:
          cpus: 10.0
          memory: 3g

networks:
  fl_network:
    driver: bridge