x-client-env: &client-env
  SERVER_URL: http://server:8000
  CUDA_VISIBLE_DEVICES: -1
  CONFIG_PATH: config/default.yaml
  CLIENT_TYPE: standard

x-client-base: &client-base
  build:
    dockerfile: dockerfiles/client.Dockerfile
  depends_on:
    server:
      condition: service_healthy
  networks:
    - fl_network
  deploy:
    resources:
      limits:
        cpus: 2.0
        memory: 3G

services:
  server:
    build:
      dockerfile: dockerfiles/server.Dockerfile
    environment:
      - CUDA_VISIBLE_DEVICES=-1
      - CONFIG_PATH=config/default.yaml
    ports:
      - "8000:8000"
    volumes:
      - ./results:/app/results
    networks:
      - fl_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 3G
          
  client_1:
    <<: *client-base
    environment:
      <<: *client-env
      CLIENT_ID: 1
      
  client_2:
    <<: *client-base
    environment:
      <<: *client-env
      CLIENT_ID: 2
      
  client_3:
    <<: *client-base
    environment:
      <<: *client-env
      CLIENT_ID: 3
      
  client_4:
    <<: *client-base
    environment:
      <<: *client-env
      CLIENT_ID: 4
      
  client_5:
    <<: *client-base
    environment:
      <<: *client-env
      CLIENT_ID: 5
      
networks:
  fl_network:
    driver: bridge