clients:
  honest_client_type: standard
  malicious_client_type: null
  malicious_percentage: 0.0
  num_clients: 15
dataset:
  name: SIGN
  non_iid: true
experiment:
  description: "Cen\xE1rio base de Federated Learning com Clustering"
  log_level: info
  name: no_attack_clustering
  output_dir: ./results
  rounds: 500
  seed: 42
model:
  batch_size: 32
  local_epochs: 5
  type: CNN_SIGN
server:
  address: 0.0.0.0:8000
  aggregation_strategy: CLUSTERING
  evaluation_interval: 1
  max_concurrent_clients: 2
  selection_fraction: 0.4
  selection_strategy: random
  type: standard
